### ISSUE TITLE
Clarify how to upgrade history package

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#102]
### Context
This is a spike card to figure out how difficult it is to do the update, and what are the dependencies.

### Timebox
2 days

### Notes
We use history for routing in certain places throughout the application. Currently we are on version 4.10.1, however there are breaking changes in version 5.0.0 because relative routes are no longer supported.

https://github.com/ReactTraining/history/releases/tag/v5.0.0

**Comment by sbhamani** [comment]
The priority of the work coming out of this is dependent on if the package is currently failing security checks. If not, it can be deprioritized until we have the bandwidth to start it.

**Comment by claireholt-tw** [comment]
In newer versions of the history package, particularly version 5.0.0 and above, relative routes are no longer supported due to breaking changes. 

We use relative routes in about 6 places in our app:
- StatusButton.js
- CaseRow.js
- EditLetter.js
- NotificationList.js
- withSecurity.js
- Auth.js (depending value of redirectUri)

Instead, you typically use absolute routes or pathnames to navigate within your application.


1. **Using absolute paths**: Instead of relying on relative paths like '../details', you would specify the absolute path directly, such as '/products/details'. This ensures that the route is resolved from the root of your application's routing hierarchy, regardless of the current location.

2. **Navigation methods:** Depending on how you're handling navigation in your application, you'll use different methods provided by the history package or your chosen routing library. For example:
- If you're using React Router, you might use the Link component with the to prop set to the absolute path: <Link to="/products/details">Details</Link>.
- If you're programmatically navigating, you might use history.push('/products/details') instead of relying on relative paths.

3. **Dynamic route generation**: If you're dynamically generating routes based on data or user input, ensure that you construct absolute paths correctly to avoid unexpected behavior. You may need to concatenate path segments or use helper functions provided by your routing library to generate absolute paths.

By transitioning to absolute routes, you ensure clarity and consistency in your routing logic, making it easier to understand and maintain your codebase over time.

**Comment by mariahsager-tw** [comment]
**Spike outcomes:**

- We know that the version of the `history package does not support relative routes, so as @claireholt-tw mentioned in the above comment, we will need to revise routes in about 6 files. This should be super easy.
- Upgrading the version of `history` also causes the error `Could not find router reducer in state tree, it must be mounted under "router"`. Here are some potential resources on how to approach this error:
  - https://stackoverflow.com/questions/54315988/connectedrouter-error-could-not-find-router-reducer-in-state-tree-it-must-be-m
  - https://dev.to/harukakato35/error-could-not-find-router-reducer-in-state-tree-it-must-be-mounted-under-router-gca
  - https://aronschueler.de/blog/2022/02/14/router-reducer-must-be-mounted-under-router/
- This seems like it should also be a relatively easy fix.

**Comment by heliofreitastw** [comment]
With the current project situation we will not be able to update the history package. 

When the package is updated, we face the following error: `Could not find router reducer in state tree, it must be mounted under "router”`.

This error is happening for several routes in the app. For example, clicking on the menu of the top right corner and clicking to open the data datasboard page causes the error to happen (the data dashboard page does not open). The same behavior happens when a click to open different pages happens. 

Going through the links provided in the spike card #102. We learned that we already have the implementation suggested in [this link](https://stackoverflow.com/questions/54315988/connectedrouter-error-could-not-find-router-reducer-in-state-tree-it-must-be-m) in your codebase.  Also, another answer from the same link says that history version 5.0.0 is only compatible with react-router-dom version 6 or above. Currently in the project we use version 5.1.0 for react-router-dom. 

I found [this link](https://reactrouter.com/en/main/upgrading/v5) on upgrading react-router-dom.
