### ISSUE TITLE
Onboard Paul (Dev)

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#512]
### Member attends relevant onboarding sessions
- [x] Team meet and greet (right before first standup) (PdM) - scheduled
- [x] Account Overview (PdM, TL, XD) - scheduled
   - Intro to team, roles, stakeholders and WoW
   - Intro and demo of the product
- [x] Overview of technical architecture, tech stack and technical deep dive (TL)

###  Role based checklist
All
- [x] Go through onboarding checklist on Trello (https://trello.com/b/ou7Ddhvt/on-off-boarding-template)

Dev
- [x] Pair with another dev to go through the dev specific onboarding items

###  Notes
- Add any blockers/issues to comments in this card

###  Access 
- [x] Slack
- [x] Github
- [x] Team calendar 
- [x] Trello

**Comment by paul-thompson1** [comment]
### Some blockers I have for completing the onboarding checklist
**Codebase**

- Do I need the following to add the following environment variables?

- REACT_APP_GOOGLE_API_KEY?

- TEST_USER?

- TEST_PASS?

**NOTE:** I had some difficulty with installing dependencies due to my CPU architecture being ARM64

**PDM Google Group**

- Who should I ask to add me to the group?

**Auth0 App User - CI/Staging/Prod**

- Who should I ask to add me as a user? How can I confirm I’ve been added?

**Auth0 Admin - CI/Staging/Prod**

- Who should I ask to add me as an admin? How can I confirm I’ve been added?

**Heroku**

- What do I need to do to get access to Heroku?

**Elastic**

- Do I add myself to Elastic or does someone else?

**Okta**

- How do I check that I’ve been added to “People” and the group “Boss”?

**Setup local DB**

- Do I install dbeaver-community and postgresql via homebrew? What version of postgresql do I need to install?

**New Relic**

- Do I need access to New Relic?

**Comment by rnair-tw** [comment]
added paul to figma

**Comment by paul-thompson1** [comment]
### Could not run yarn install with node v16
Note: Solved

Background:
There are no ARM64 binaries for the dependency node-canvas. I had to troubleshoot the errors I received.

Expected behavior: yarn install completes without errors

Actual behavior: yarn install does not complete. Error raised in terminal.

**Python module not installed (distutils)**
I first noticed that distutils was not available even though I had python 3.12 installed. After some research I found that distutils was not available in  python 3.12. So I setup a pyenv with python 3.10.10. 

**Here are steps:**
`brew install pyenv`
`pyenv global 3.10.10`

Edit the file
`nano ~/.zshrc`

Add the following to the bottom of the file
`eval "$(pyenv init --path)"`

Save and exit (CTRL+O, CTRL+X)
Quit terminal & Reopen terminal


Test the python version
`python3 --version`

Go to cloned repo. Assumed you installed nvm, yarn and are using node version 16
`yarn install`

You should now get a success message:
<img width="270" alt="Screenshot 2024-04-01 at 5 19 43 PM" src="https://github.com/PublicDataWorks/complaint-manager/assets/159827724/cfe2bea2-0607-421c-b8e4-c887c3804914">
