### ISSUE TITLE
Investigate "assigned to" initials format

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#534]
Investigate why assignment initials are first 2 letters of FirstName for some people as opposed to FirstName and LastName initials. This is also inconsistent (some ppl have first 2 letters, some have initials). This was a question from Hawaii as they want it to be the initials. 

Steps:
- Check for Hawaii (Okta)
- Check for New Orleans (Auth0)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/19675b9e-377a-41c3-9278-f39eacd849ab)

**Comment by justin-c-anthony** [comment]
The Initials are coming from the user's email which we get from Okta.

We take the Okta email (itrs called "nickname" and parse out the first two letters of the email and display those as the initials.

This happens in the UserAvatar.js component:

```
const UserAvatar = props => {
  const classes = useStyles();

  if (props.email) {
    const initials = props.email.substring(0, 2).toUpperCase();

    return (
      <div>
        <Tooltip data-testid={`tooltip-${initials}`} title={props.email}>
          <Avatar className={classes.avatar}>{initials}</Avatar>
        </Tooltip>
      </div>
    );
  } else {
    return <div data-testid="no-avatar"></div>;
  }
};

export default UserAvatar;
```

In order to fix this, we will need to look into Okta dashboard and and set up a method to retrieve the user name as well as their nickname and adjust our okta API call in the app to retrieve this data.

**Comment by rnair-tw** [comment]
Added @552 for implementation work
