### ISSUE TITLE
Job Jar requests

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#616]
Card to track all the job jar requests posted: https://trello.com/b/QuD7Ykrs/us-beach-job-jar

- Set up back-end with best practices (i.e. API framework, CI pipeline, docker setup, other infra setup) https://trello.com/c/39hL4QZK/143-2-week-support-for-social-change-project-for-sr-developer (claimed by Vivian Liao)

**Comment by rnair-tw** [comment]
Potential ideas:
- Do a POC for content management system for form creation
- Do a POC for physical letter to case creation

**Comment by sbhamani** [comment]
- POC for using an OCR to scan handwritten letters and extract useful info from it using Gen AI in order to automate data entry (same concept can be applied to electronic letters w/o the step of using an OCR)
   - Who is the complainant?
   - Who is the accused?
   - Demographic info (i.e. Facility name, address, phone numbers, etc.)
   - Summary of complaint
   - Generate a custom response letter
- Chatbot to educate several types of audiences about prison/police reform

**Comment by rnair-tw** [comment]
- For Pulomi, build the UI to make it self-service, simple web-app

**Comment by rnair-tw** [comment]
tracked in v2 board
